build_script:
    - pwsh: |
          $ErrorActionPreference = "Stop"
          Set-StrictMode -Version 2.0
          markdownlint *.md
image: Visual Studio 2019 Preview
install:
    - pwsh: |
          $ErrorActionPreference = "Stop"
          Set-StrictMode -Version 2.0
          npm install markdownlint-cli -g
pull_requests:
    do_not_increment_build_number: true
skip_tags: true
