name: CI
on:
    push:
    pull_request:
        types:
            - edited
            - opened
            - reopened
            - synchronize
jobs:
    ci:
        runs-on: windows-latest
        steps:
            - uses: xt0rted/markdownlint-problem-matcher@v1
            - name: Clone repository
              uses: actions/checkout@v2.3.2
            - name: Install dependencies
              shell: pwsh
              run: |
                  npm install markdownlint-cli@0.23.2 -g
            - name: Lint Markdown files
              shell: pwsh
              run: |
                  markdownlint *.md
