# Reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: News
on:
    issues:
        types:
            - opened
    pull_request:
        types:
            - opened
jobs:
    news:
        runs-on: windows-latest
        steps:
            - name: Permission check
              id: permission
              uses: lannonbr/repo-permission-check-action@2.0.1
              with:
                  permission: write
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              continue-on-error: true
            - name: Close issue
              if: steps.permission.outcome == 'failure'
              uses: peter-evans/close-issue@v1.0.1
              with:
                  comment: |
                      Please do not open issues or pull requests on this repository.
            - name: Lock issue
              uses: OSDKDev/lock-issues@v1.1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
            - name: Notify Discord
              if: github.event_name == 'issues' && github.repository == 'flare-lang/flare-news' && steps.permission.outcome == 'success'
              uses: hugoalh/GitHubAction.SendToDiscord@v1.1.6
              with:
                  webhook_id: ${{ secrets.DISCORD_NEWS_ID }}
                  webhook_token: ${{ secrets.DISCORD_NEWS_TOKEN }}
                  message_embed_authorname: ${{ github.event.issue.user.login }}
                  message_embed_authorurl: ${{ github.event.issue.user.html_url }}
                  message_embed_title: ${{ github.issue.event.title }}
                  message_embed_titleurl: ${{ github.event.issue.html_url }}
                  message_embed_description: ${{ github.event.issue.body }}
